name: Generate and Publish Javadoc

on:
  push:
    branches:
      - main

jobs:
  generate-and-publish-javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Publish Javadoc to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs/