  on: push
  jobs:
    job1:
      runs-on: ubuntu-latest #Tourne sur une VM ubuntu
      steps: #Etapes à réaliser sur le système
        #On se place dans le dépôt...
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Set up JDK
          uses: actions/setup-java@v1
          with:
            java-version: '17'

        - name: Build with Maven
          run: mvn -B package --file pom.xml
        - name: Run Unit Tests
          run: mvn test --file pom.xml